name: cowaver
channels:
  - pytorch
  - conda-forge
dependencies:
  - numpy
  - pillow
  - pysoundfile
  - sympy
  - scipy
  - pytorch=2.4.1
  - torchaudio
  - torchvision
  - safetensors
  - transformers
  - matplotlib-base
  - notebook
  - ipywidgets
